coverage:
  range: 70..90
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
ignore:
  - "tests"
  - "include/fast_matrix_market/3rdparty"
  - "dependencies"
